;; Chicken Scheme 5
(import (chicken sort) (srfi-1))

;; SEPA by Jeffrey Johnson. First input must be sorted.
;; https://web.archive.org/web/20041118122557/http://www.cs.byuh.edu/~johnsonj/permute/soda_submit.html
(define (permute! v less)
  (define (sub-vector-min k)
    (do ((i (- (vector-length v) 1) (- i 1)))
	((less k (vector-ref v i)) i)))
  (define (vector-swap! i j)
    (let ((x (vector-ref v i)))
      (vector-set! v i (vector-ref v j))
      (vector-set! v j x)))
  (define (sort-tail! i)
    (do ((i i (+ i 1))
	 (j (- (vector-length v) 1) (- j 1)))
	((>= i j))
      (vector-swap! i j)))
  (let loop ((i (- (vector-length v) 2)))
    (cond ((< i 0) #f) ; no more permutations
	  ((less (vector-ref v i) (vector-ref v (+ i 1)))
	   ;; found the key, find minimum to the right of key
	   (let ((j (sub-vector-min (vector-ref v i))))
	     (vector-swap! i j)
	     (sort-tail! (+ i 1))
	     #t))
	  (else (loop (- i 1))))))

(define 3gon-map '((6 . #(0 3 4 1 4 5 2 5 3))
		   (10 . #(0 5 6 1 6 7 2 7 8 3 8 9 4 9 5))))

(define (solve n)
  (define (sum lst) (foldl + 0 lst))
  (define (concat pre lst)
    (foldl (lambda (pre x) (string-append pre (number->string x)))
	   pre lst))
  (define (3gon-triplet v index i)
    (let ((triplet (map (lambda (j) (vector-ref v (vector-ref index (+ (* 3 i) j))))
			(iota 3))))
      (values triplet (sum triplet))))
  (define (3gon-min-outer-first? v n-triplets)
    (let loop ((i 1))
      (cond ((>= i n-triplets) #t)
	    ((< (vector-ref v 0) (vector-ref v i)) (loop (+ i 1)))
	    (else #f))))
  (assert (integer? (/ n 2)))
  (let ((v (list->vector (cdr (iota (+ n 1)))))
	(n-triplets (/ n 2))
	(3gon-index (cdr (assv n 3gon-map))))
    (do ((ok #t (permute! v <)) (max 0))
	((not ok) (print `(max ,max)))
      (if (3gon-min-outer-first? v n-triplets)
	  (receive (first first-sum) (3gon-triplet v 3gon-index 0)
	    (let loop ((j 1) (x (concat "" first)))
	      (if (= j n-triplets)
		  ;; hack for n=10 and 16 digits
		  (if (or (not (= n 10)) (= (string-length x) 16))
		      (let ((x (string->number x)))
			(print x)
			(if (> x max) (set! max x))))
		  (receive (next next-sum) (3gon-triplet v 3gon-index j)
		    (if (= first-sum next-sum)
			(loop (+ j 1) (concat x next)))))))))))

(solve 10)
