;; Chicken Scheme 5
(define *max* 1000000)
(define *sieve* (make-vector (+ *max* 1) 0))

(do ((i 2 (+ i 1)))
    ((> i *max*))
  (when (= (vector-ref *sieve* i) 0)
    (do ((j (+ i i) (+ j i))
	 (x 1))
	((> j *max*))
      (let ((y (vector-ref *sieve* j)))
	(if (= y 0)
	    (begin (vector-set! *sieve* j x)
		   (set! x (+ x 1)))
	    (vector-set! *sieve* j (+ x y)))))))

(let ((max-ratio 0) (max-n 0))
  (do ((n 2 (+ n 1)))
      ((> n *max*))
    (let* ((φ (- n 1 (vector-ref *sieve* n)))
	   (ratio (/ n φ)))
      (when (> ratio max-ratio)
	(set! max-ratio ratio)
	(set! max-n n))))
  (print max-n))
