(import srfi-1 miscmacros)
(define *factorials* (make-vector 10))
(foldl (lambda (prev n)
	 (let ((x (if (= n 0) 1 (* prev n)))) (vector-set! *factorials* n x) x)) 0 (iota 10))
(define *max* 1000000)
(define (factorial-digit-sum n)
  (foldl + 0 (map (lambda (ch) (vector-ref *factorials* (- (char->integer ch) 48)))
		  (string->list (number->string n)))))
(define *table* (make-vector (+ 1 *max*) #f))
(define (store! n x) (if (<= n *max*) (vector-set! *table* n x)))
(define (store-all! x rev-list)
  (receive (cycle rest) (split-at rev-list (+ 1 (list-index (cut = x <>) rev-list)))
    (let ((len (length cycle)))
      (for-each (lambda (y) (store! y len)) cycle)
      (do ((n (+ len 1) (+ 1 n)) (iter rest (cdr iter)))
	  ((null? iter))
	(store! (car iter) n)))))
(define (count-sequence! n)
  (let loop ((i n) (rev-list '()))
    (if (member i rev-list)
	(store-all! i rev-list)
	(if* (and (<= i *max*) (vector-ref *table* i))
	     (store! n (+ it (length rev-list)))
	     (loop (factorial-digit-sum i) (cons i rev-list))))))
(do ((i 1 (+ 1 i))) ((> i *max*)) (count-sequence! i))
(let count-loop ((i 1) (count 0))
  (if (> i *max*) (print count)
      (let ((c (vector-ref *table* i)))
	(count-loop (+ 1 i) (if (and c (= c 60)) (+ count 1) count)))))
