;; Chicken Scheme 5
(import srfi-113 srfi-128 (chicken sort))
(define (make-set . rest) (apply set (make-default-comparator) rest))
(let* ((max-n 100)
	   (cache (make-vector (+ max-n 1))))
  (vector-set! cache 1 (make-set))
  (do ((i 2 (+ i 1)))
	  ((> i max-n))
	;; (print `(i ,i))
	(let ((mid (floor (/ i 2))))
	  (let loop ((x 1) (s (make-set)))
		(if (> x mid)
			(begin
			  (print (list i (set-size s)))
			  (vector-set! cache i s))
			(let* ((y (- i x))
				   (x-set (vector-ref cache x))
				   (y-set (vector-ref cache y))
				   ;; (_ (print `(x ,x x-set ,x-set y ,y y-set ,y-set)))
				   )
			  (loop (+ x 1)
					(set-fold (lambda (x-sum s)
								(set-fold (lambda (y-sum s)
											(set-adjoin s (sort (append x-sum y-sum) <)))
										  s (set-adjoin y-set (list y))))
							  s (set-adjoin x-set (list x))))))))))
